// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEgdUGXh1sXNGBCl7s76wS5wdKzloOjr0',
    appId: '1:672796381698:web:f176f58912887cb3ea8d1b',
    messagingSenderId: '672796381698',
    projectId: 'pac-04-2022-1',
    authDomain: 'pac-04-2022-1.firebaseapp.com',
    storageBucket: 'pac-04-2022-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVQHH6gt-qOww2pNVn0JL22kAwglzG5U',
    appId: '1:672796381698:android:17c29ef04a3fefdcea8d1b',
    messagingSenderId: '672796381698',
    projectId: 'pac-04-2022-1',
    storageBucket: 'pac-04-2022-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGYSplftaHDEnMX0HPMiZIT1j7gevfeH0',
    appId: '1:672796381698:ios:9f4e366b6068dfaeea8d1b',
    messagingSenderId: '672796381698',
    projectId: 'pac-04-2022-1',
    storageBucket: 'pac-04-2022-1.appspot.com',
    iosClientId: '672796381698-rabiheuni35vgotf3r95c8nd5sefttad.apps.googleusercontent.com',
    iosBundleId: 'com.example.pac04',
  );
}
